services:
  app:
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - DOCKER_DATABASE_URL=${DOCKER_DATABASE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
