services:
  app:
    environment:
      - DATABASE_URL=postgresql://otp_user:otp_password@db:5432/otp_ds
      - DOCKER_DATABASE_URL=${DOCKER_DATABASE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
